#spring:
#  datasource:
#   url: jdbc:mysql://45.118.162.234:3306/accord
#   username: root
#   password: Idbi@5996
#  h2:
#   console: 
#    enabled: true
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#
#      
#  application:
#    name: accord
# #=======================JPA/H/bernate Details===================================
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect 
#   
#  
#        
#        
#hibernate:
# format_sql: true 
#    
#  
#
#
